on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create release

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Extract version tag
        id: version
        run: echo ::set-output name=value::$(echo ${{ github.ref }} | cut -f 3 -d / | sed "s/^v//" )

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_RELEASE }}
        with:
          tag_name: release_${{ github.ref }}
          release_name: ${{ steps.version.outputs.value }}

