on:
  push:
    tags:
    - 'cargo-dinghy/*'

name: Create release

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Extract version tag
        id: version
        run: echo ::set-output name=value::$(echo ${{ github.ref }} | cut -f 4 -d /)

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_RELEASE }}
        with:
          tag_name: v${{ steps.version.output.value }}
          release_name: ${{ steps.version.outputs.value }}

